import { Modal, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { BorderRadius, Colors } from '../theme';
import { HOMEWARD_LANGUAGES, useLanguage } from '../i18n/LanguageContext';

export default function LanguagePicker({ visible, onClose }: { visible: boolean; onClose: () => void }) {
  const { language, languageName, setLanguage } = useLanguage();
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={styles.overlay}><TouchableOpacity style={StyleSheet.absoluteFill} activeOpacity={1} onPress={onClose} /><View style={styles.sheet}><View style={styles.head}><View><Text style={styles.title}>Choose your language</Text><Text style={styles.subtitle}>This choice stays with HomeWard on this device.</Text></View><TouchableOpacity onPress={onClose}><MaterialCommunityIcons name="close" size={22} color={Colors.onSurfaceVariant} /></TouchableOpacity></View>{HOMEWARD_LANGUAGES.map((item) => <TouchableOpacity key={item.code} style={[styles.option, item.code === language && styles.selected]} onPress={() => { setLanguage(item.code); onClose(); }}><MaterialCommunityIcons name="translate" size={18} color={item.code === language ? Colors.onPrimary : Colors.primary} /><Text style={[styles.optionText, item.code === language && styles.selectedText]}>{item.name}</Text>{item.code === language ? <MaterialCommunityIcons name="check" size={18} color={Colors.onPrimary} /> : null}</TouchableOpacity>)}</View></View></Modal>;
}
export function LanguageButton({ onPress, compact = false }: { onPress: () => void; compact?: boolean }) { const { languageName } = useLanguage(); return <TouchableOpacity style={[styles.button, compact && styles.compactButton]} onPress={onPress}><MaterialCommunityIcons name="translate" size={17} color={Colors.primary} /><Text numberOfLines={1} style={styles.buttonText}>{languageName}</Text></TouchableOpacity>; }
const styles = StyleSheet.create({ overlay:{flex:1,backgroundColor:'rgba(0,32,25,0.48)',justifyContent:'flex-end'},sheet:{backgroundColor:Colors.surfaceContainerLowest,borderTopLeftRadius:24,borderTopRightRadius:24,padding:20,paddingBottom:30},head:{flexDirection:'row',justifyContent:'space-between',gap:12,marginBottom:12},title:{fontFamily:'Montserrat',fontSize:20,fontWeight:'800',color:Colors.onSurface},subtitle:{fontFamily:'Inter',fontSize:12,color:Colors.onSurfaceVariant,marginTop:5},option:{padding:12,borderRadius:13,flexDirection:'row',gap:11,alignItems:'center'},selected:{backgroundColor:Colors.primary},optionText:{flex:1,fontFamily:'Inter',fontSize:14,fontWeight:'800',color:Colors.onSurface},selectedText:{color:Colors.onPrimary},button:{height:38,maxWidth:130,paddingHorizontal:11,borderRadius:19,backgroundColor:Colors.primaryFixed,alignItems:'center',flexDirection:'row',gap:6},compactButton:{height:34},buttonText:{flexShrink:1,fontFamily:'Inter',fontSize:11,fontWeight:'800',color:Colors.primary} });
